server:
  port: 8091
  servlet:
    context-path: /
jt:
  rabbitmq:
    enable: true

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jtdb?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
    username: root
    password: 123456
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: # 如果未单独配置默认为空即可
    timeout: 1000
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0

#reids相关配置
#redis服务器地址
  #spring.redis.host=localhost
  #雷迪森服务器端口
  #spring.redis.port=6379
  #redis密码，默认为空
  #spring.redis.password=
  #redis数据库索引（默认为0）
  #spring.redis.database=0
  #连接池对打阻塞等待时间（负表示没有限制）
  #spring.redis.jedis.pool.max-wait=10000
  #连接池最大连接数(负表示没有限制)
  #spring.redis.jedis.pool.max-active=100
  #连接池中的最大空闲链接
  #spring.redis.jedis.pool.max-idle=20
  #连接池中的最小空闲链接
  #spring.redis.jedis.pool.min-idle=0
  #链接超时时间
  #spring.redis.timeout=3000

  rabbitmq:
    host:
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    publisher-confirms: true
    publisher-returns: true
    template:
      mandatory: true
    listener:
      type: simple
      simple:
        acknowledge-mode: manual


mybatis-plus:
  type-aliases-package: com.aike.pojo
  mapper-locations: classpath:/mybatis/mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    com.aike.mapper: debug


